CREATE DATABASE Amazon;
Use Amazon


CREATE TABLE `amazon`.`TblUserssss` (
`sdasd` VARCHAR(55) NOT NULL ,
`sada` INT(5) NULL )
ENGINE = InnoDB;


CREATE TABLE Wish_Product (
WishIDVARCHAR(12) NOT NULL ,
Product_IdVARCHAR(12) NOT NULL ,
PRIMARY KEY(WishID, Product_Id),
FOREIGN KEY (WishID) REFERENCES WishList(WishID),
FOREIGN KEY (Product_Id) REFERENCES Products(Product_Id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Product_seller (
SellerIdVARCHAR(12) NOT NULL ,
Product_IdVARCHAR(12) NOT NULL ,
PRIMARY KEY(SellerId),
FOREIGN KEY (SellerId) REFERENCES Seller(SellerId) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Product_Id) REFERENCES Products(Product_Id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Complaint (
Complaint_IdVARCHAR(12) NOT NULL ,
Type VARCHAR(12) NOT NULL ,
Date DATE NOT NULL ,
Description VARCHAR(200) NOT NULL ,
Status VARCHAR(12) NOT NULL ,
Person_idVARCHAR(12) NOT NULL ,
PRIMARY KEY(Complaint_Id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Products (
Product_IdVARCHAR(12) NOT NULL ,
Listing_idVARCHAR(12),
Max_qty INT NOT NULL ,
Category VARCHAR(12) NOT NULL ,
Size VARCHAR(5) NOT NULL ,
First_Listed DATE NOT NULL ,
Gender VARCHAR(6),
ItemConditionVARCHAR(12) NOT NULL ,
ColorVARCHAR(12) NOT NULL ,
Description VARCHAR(200) NOT NULL ,
Dimension VARCHAR(10) NOT NULL ,
Question VARCHAR(12) NOT NULL ,
List_PriceVARCHAR(12) NOT NULL ,
Actual_PriceVARCHAR(12) NOT NULL ,
Stock_size INT NOT NULL ,
Time_IntervalVARCHAR(12) NOT NULL ,
Average_ratingDECIMAL(2,1) NOT NULL ,
DISCOUNT DECIMAL(3,2) NOT NULL ,
PRIMARY KEY(Product_Id),
FOREIGN KEY (Listing_id) REFERENCES Listings(Listing_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Seller (
SellerIdVARCHAR(12) NOT NULL ,
Name VARCHAR(12) NOT NULL ,
Phone_noVARCHAR(12) NOT NULL ,
Email VARCHAR(20) NOT NULL ,
Average_ratingDECIMAL(2,1),
PRIMARY KEY(SellerId)) ;


CREATE TABLE Listings (
Listing_idVARCHAR(12) NOT NULL ,
PRIMARY KEY(Listing_id)) ;


CREATE TABLE Reviews (
Person_idVARCHAR(12) NOT NULL ,
Product_IdVARCHAR(12) NOT NULL ,
review_date DATE NOT NULL ,
Rating INT NOT NULL CHECK (Rating > 0 AND Rating <=5),
Comments VARCHAR(200),
PRIMARY KEY(Person_id,Product_Id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE,
FOREIGN KEY (Product_Id) REFERENCES Products(Product_Id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Person (
Person_idVARCHAR(12) NOT NULL ,
Name VARCHAR(30) NOT NULL ,
Email VARCHAR(200),
Password VARCHAR(200),
PRIMARY KEY(Person_id)) ;


CREATE TABLE Userdevices (
Person_idVARCHAR(12) NOT NULL ,
DeviceNameVARCHAR(200),
PRIMARY KEY(Person_id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE
) ;


CREATE TABLE Customer_rep (
Person_idVARCHAR(12) NOT NULL ,
salary DECIMAL(10,2) NOT NULL ,
Designation VARCHAR(200),
Department VARCHAR(20),
PRIMARY KEY(Person_id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE WishList (
WishIDVARCHAR(12) NOT NULL ,
Name VARCHAR(12) NOT NULL ,
Visibility VARCHAR(12) NOT NULL ,
Person_idVARCHAR(12) NOT NULL ,
PRIMARY KEY(WishID),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Cart (
Product_IdVARCHAR(12) NOT NULL ,
Person_idVARCHAR(12) NOT NULL ,
Subtotal DECIMAL(10,2) NOT NULL ,
PRIMARY KEY(Product_Id),
FOREIGN KEY (Product_Id) REFERENCES Products(Product_Id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Orders (
OrderIdVARCHAR(12) NOT NULL ,
OrderDate DATE NOT NULL ,
DeliveryDate DATE NOT NULL ,
Total DECIMAL(10,2) NOT NULL ,
ShippingTotalDECIMAL(10,2) NOT NULL ,
ReturnId VARCHAR(12) NOT NULL ,
Person_id VARCHAR(12) NOT NULL ,
PRIMARY KEY(OrderId),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE,
FOREIGN KEY (ReturnId) REFERENCES Returns(ReturnId) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Transaction (
TidVARCHAR(12) NOT NULL ,
TDate DATE NOT NULL ,
Status VARCHAR(12) NOT NULL ,
Amount DECIMAL(10,2),
Time TIME NOT NULL ,
Method VARCHAR(10),
CardNoVARCHAR(20) NOT NULL ,
PRIMARY KEY(Tid),
FOREIGN KEY (CardNo) REFERENCES PaymentMethods(CardNo)ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Cards (
CardNoVARCHAR(20) NOT NULL ,
Type VARCHAR(10) NOT NULL ,
CVV VARCHAR(3) ,
PRIMARY KEY(CardNo),
FOREIGN KEY (CardNo) REFERENCES PaymentMethods(CardNo) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE PaymentMethods (
CardNoVARCHAR(20) NOT NULL ,
ValidThrough DATE NOT NULL ,
Person_idVARCHAR(12) NOT NULL ,
PRIMARY KEY(CardNo)) ;


CREATE TABLE GiftCards (
CardNoVARCHAR(20) NOT NULL ,
Balance DECIMAL(8,2) NOT NULL ,
PRIMARY KEY(CardNo),
FOREIGN KEY (CardNo) REFERENCES PaymentMethods(CardNo) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Returns (
ReturnIdVARCHAR(12) NOT NULL ,
ItemConditionVARCHAR(12) NOT NULL ,
ReturnModeVARCHAR(12) NOT NULL ,
Status VARCHAR(12) NOT NULL ,
TrackingCodeVARCHAR(20) NOT NULL ,
Qty INT NOT NULL ,
Date DATE NOT NULL ,
Reason VARCHAR(12) NOT NULL ,
TransactionIdVARCHAR(12) NOT NULL ,
PRIMARY KEY(ReturnId),
FOREIGN KEY (TransactionId) REFERENCES Transaction(Tid) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Memberships (
Mid VARCHAR(12) NOT NULL ,
ValidThrough DATE NOT NULL ,
Autorenew BOOLEAN NOT NULL ,
SnameVARCHAR(12) NOT NULL ,
Person_idVARCHAR(12) NOT NULL ,
TransactionIdVARCHAR(12) NOT NULL ,
PRIMARY KEY(Mid),
FOREIGN KEY (Sname) REFERENCES Services(Name) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (TransactionId) REFERENCES Transaction(Tid) ON DELETE CASCADE ON UPDATE
CASCADE,
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Services (
Name VARCHAR(12) NOT NULL ,
Price DECIMAL(8,2) NOT NULL ,
TimeInMonths INT NOT NULL ,
PRIMARY KEY(Name)) ;


CREATE TABLE Address (
Person_idVARCHAR(12) NOT NULL ,
AptNOVARCHAR(10) NOT NULL ,
Street VARCHAR(20) NOT NULL ,
City VARCHAR(12) NOT NULL ,
State VARCHAR(12) NOT NULL ,
Country VARCHAR(12) NOT NULL ,
ZIPCodeVARCHAR(10) NOT NULL ,
PRIMARY KEY(Person_id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;


CREATE TABLE Phone (
Person_idVARCHAR(12) NOT NULL ,
Phone_noVARCHAR(13) NOT NULL ,
PRIMARY KEY(Person_id),
FOREIGN KEY (Person_id) REFERENCES Person(Person_id) ON DELETE CASCADE ON UPDATE
CASCADE) ;